apiVersion: apps/v1
kind: Deployment
metadata:
  name: acl-api
  namespace: acl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acl-api
  template:
    metadata:
      labels:
        app: acl-api
    spec:
      containers:
        - name: api
          image: localhost:5001/acl-api:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_DB
            - name: ACL_CONFIG_PATH
              value: /config/config.yaml
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: acl-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: acl-api
  namespace: acl
spec:
  selector:
    app: acl-api
  ports:
    - port: 80
      targetPort: 3000
      name: http
